#!/usr/bin/perl -w
# checks if a relaxed plan exists for the problem in the domain
use File::Basename;

if ((scalar @ARGV) != 2) {
	print "Usage: rp_exists <domain> <problem>\n";
	exit(1);
}

$dir = dirname(__FILE__);
$dom = shift @ARGV;
$prob = shift @ARGV;

if (!(-e $dom)) {
	print "Domain file $dom not found\n";
	exit(1);
}

if (!(-e $prob)) {
  print "Problem file $prob not found\n";
  exit(1);
}

system("$dir/bin/colin-clp", "-j", "$dom", "$prob");
# get return value of the executable
$exit_code = $? >> 8;
exit($exit_code);
