(define (problem edgeware)

	(:domain automated-drone-delivery)

	(:objects drone1 drone2 drone3 - drone
			  package1 package2 package3 package4 package5 package6 package7 - package
			  warehouse1 warehouse2 customer1 customer2 customer3 customer4 - location)

	(:init
		(at-drone drone1 warehouse1)
		(at-drone drone2 warehouse1)
		(at-drone drone3 warehouse1)
		(at-package package1 warehouse1)
		(at-package package2 warehouse1)
		(at-package package3 warehouse1)
		(at-package package4 warehouse2)
		(at-package package5 warehouse2)
		(at-package package6 warehouse2)
		(at-package package7 warehouse2)
		(drone-empty drone1)
		(drone-empty drone2)
		(drone-empty drone3)
		(is-warehouse warehouse1)
		(is-warehouse warehouse2)
		(= (capacity) 50)
		(= (charge drone1) 50)
		(= (charge drone2) 50)
		(= (charge drone3) 50)
		(= (weight package1) 50)
		(= (weight package2) 50)
		(= (weight package3) 50)
		(= (weight package4) 50)
		(= (weight package5) 70)
		(= (weight package6) 70)
		(= (weight package7) 80)
		(= (move-time warehouse1 warehouse2) 10)
		(= (move-time warehouse1 customer1) 4)
		(= (move-time warehouse1 customer2) 8)
		(= (move-time warehouse1 customer3) 12)
		(= (move-time warehouse1 customer4) 16)
		(= (move-time customer1 warehouse1) 4)
		(= (move-time customer2 warehouse1) 8)
		(= (move-time customer3 warehouse1) 12)
		(= (move-time customer4 warehouse1) 16)
		(= (move-time warehouse2 customer1) 16)
		(= (move-time warehouse2 customer2) 12)
		(= (move-time warehouse2 customer3) 8)
		(= (move-time warehouse2 customer4) 4)
		(= (move-time customer1 warehouse2) 16)
		(= (move-time customer2 warehouse2) 12)
		(= (move-time customer3 warehouse2) 8)
		(= (move-time customer4 warehouse2) 4)
		(= (load-time) 1))

	(:goal (and
		(at-drone drone1 warehouse1)
		(at-drone drone2 warehouse1)
		(at-drone drone3 warehouse1)
		(at-package package1 customer1)
		(at-package package2 customer2)
		(at-package package3 customer3)
		(at-package package4 customer3)
		(at-package package5 customer4)
		(at-package package6 customer4)
		(at-package package7 customer4)))
)