#!/usr/bin/perl -w
use File::Basename;

if ((scalar @ARGV) != 4) {
	print "Usage: plan <domain> <problem> <solution> <timing>\n";
	exit(1);
}

$dir = dirname(__FILE__);
$dom = shift @ARGV;
$prob = shift @ARGV;
$soln = shift @ARGV;
$timing = shift @ARGV;

if (!(-e $dom)) {
	print "Domain file $dom not found\n";
	exit(1);
}

if (!(-e $prob)) {
        print "Problem file $prob not found\n";
        exit(1);
}

#open IN, "$dir/compile/popf2/popf3-clp -I $dom $prob |";
#
#$solnfile = 1;
#while (<IN>) {
#	if (m/; Plan found/) {
#		print "\n\n - Opening plan file $soln.$solnfile\n";
#		print;
#		open OUT, "> $soln.$solnfile";
#		print OUT;
#		while (<IN>) {
#			if (m/./) {
#				print;
#				print OUT;
#			} else {
#				print;
#				last;
#			}
#		}
#		close OUT;
#		++$solnfile;
#	} else {
#		print;
#	}
#
#}
#
#close IN;

#exec("$dir/compile/popf2/popf3-clp", "-b", "-e", "-I", "-y", "$timing", "-a", "$soln", "$dom", "$prob")

exec("$dir/compile/popf2/popf3-clp", "-b", "-e", "-I", "-y", "$timing", "-a", "$soln", "$dom", "$prob")
